# Generated by Django 2.1.5 on 2019-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delivery',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='award',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects_credits',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='nfq',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='ote_flag',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
