# Generated by Django 2.1.7 on 2019-02-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=255)),
                ('ects_credits', models.IntegerField()),
                ('mode', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nfq', models.IntegerField()),
                ('ote_flag', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
            ],
        ),
    ]
