# Generated by Django 2.1.7 on 2019-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects_credits',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='nfq',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='ote_flag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
