# Generated by Django 2.2 on 2020-10-23 14:04

import core.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=255)),
                ('provider', models.CharField(default='none', max_length=255)),
                ('award', models.CharField(default='none', max_length=255)),
                ('ects_credits', models.CharField(default='0', max_length=255)),
                ('mode', models.CharField(default='none', max_length=255)),
                ('deadline', models.CharField(default='1/1/2022', max_length=255)),
                ('start_date', models.CharField(default='1/1/2022', max_length=255)),
                ('end_date', models.CharField(default='1/1/2023', max_length=255)),
                ('nfq', models.CharField(default='0', max_length=255)),
                ('ote_flag', models.CharField(default='none', max_length=255)),
                ('link', models.CharField(default='none', max_length=255)),
                ('skills', models.CharField(default='none', max_length=255)),
                ('delivery', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='OK', max_length=254)),
                ('updated', models.DateTimeField(default=datetime.datetime(2020, 10, 23, 15, 4, 44, 331141))),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='guest', max_length=254)),
                ('image', models.ImageField(default='portraits/default.jpg', upload_to=core.utils.content_file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
