# Generated by Django 2.2 on 2020-11-03 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201103_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemodel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 10, 52, 39, 325295)),
        ),
    ]
