# Generated by Django 2.1.7 on 2019-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190228_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ects_credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
